/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import conexao.Conexao;
import conexao.InformacoesSistema;
import conexao.Prontuario;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alana
 */
public class CadastroProntuario extends javax.swing.JFrame {

    Conexao conexao;
    Connection con;

    String sql = "select dataconsulta,descricao from consulta where crm= " + InformacoesSistema.crm + "and idpaciente= " + InformacoesSistema.idpaciente + "order by dataconsulta desc";

    /**
     * Creates new form CadastroProntuario
     */
    public CadastroProntuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbNomeMed = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNomePac = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDataConsulta = new javax.swing.JFormattedTextField();
        buInserir = new javax.swing.JButton();
        buAlterar = new javax.swing.JButton();
        buExcluir = new javax.swing.JButton();
        buLimparCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescricao = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Prontuário ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbNomeMed.setText("Nome do Médico");

        jLabel2.setText("Paciente:");

        lbNomePac.setText("Nome do Paciente");

        jLabel4.setText("Data:");

        try {
            tfDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buInserir.setText("Inserir");
        buInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buInserirActionPerformed(evt);
            }
        });

        buAlterar.setText("Alterar");
        buAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarActionPerformed(evt);
            }
        });

        buExcluir.setText("Excluir");
        buExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExcluirActionPerformed(evt);
            }
        });

        buLimparCampos.setText("Limpar Campos");
        buLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buLimparCamposActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tfDescricao);

        jLabel5.setText("Descrição:");

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data da Consulta", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbNomeMed)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbNomePac))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfDataConsulta)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buInserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buLimparCampos)))
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbNomeMed)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbNomePac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buInserir)
                    .addComponent(buAlterar)
                    .addComponent(buExcluir)
                    .addComponent(buLimparCampos))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(452, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // Metodo de abertura do formulário
        String frase = "Seja Bem Vindo Dr." + InformacoesSistema.nome_medico + " - CRM " + InformacoesSistema.crm;
        lbNomeMed.setText(frase);
        lbNomePac.setText(InformacoesSistema.nome_paciente);

        //Conectando o Banco
        conexao = new Conexao();
        con = conexao.Conectar();

        try {
            PreencherTabela(sql);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProntuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*  String sql = "select dataconsulta,descricao from consulta"
                + "where crm= " + InformacoesSistema.crm + "and idpaciente= " + InformacoesSistema.idpaciente
                + "order by dataconsulta desc";*/

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        conexao.Desconectar();
    }//GEN-LAST:event_formWindowClosing

    private void buLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buLimparCamposActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_buLimparCamposActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:
        int linha = Tabela.getSelectedRow();

        tfDataConsulta.setText(Tabela.getValueAt(linha, 0).toString());
        tfDescricao.setText(Tabela.getValueAt(linha, 1).toString());
    }//GEN-LAST:event_TabelaMouseClicked

    private void buInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buInserirActionPerformed
        // TODO add your handling code here:
        Prontuario prontuario = new Prontuario();
        Integer CRM = InformacoesSistema.crm;
        Integer IdPaciente = InformacoesSistema.idpaciente;
        try {
            prontuario.Inserir(con, CRM, IdPaciente, tfDataConsulta.getText(), tfDescricao.getText());
            PreencherTabela(sql);
            LimparCampos();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProntuario.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buInserirActionPerformed

    private void buAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarActionPerformed
        // TODO add your handling code here:
        Prontuario prontuario = new Prontuario();
        Integer crm = InformacoesSistema.crm;
        Integer idpaciente = InformacoesSistema.idpaciente;
        try {
            prontuario.Alterar(con, crm, idpaciente, tfDataConsulta.getText(), tfDescricao.getText());
            PreencherTabela(sql);
            LimparCampos();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProntuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buAlterarActionPerformed

    private void buExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExcluirActionPerformed
        // TODO add your handling code here:

        Prontuario prontuario = new Prontuario();
        Integer crm = InformacoesSistema.crm;
        Integer idpaciente = InformacoesSistema.idpaciente;

        try {
            prontuario.Excluir(con, crm, idpaciente, tfDataConsulta.getText());
            PreencherTabela(sql);
            LimparCampos();
        } catch (ParseException ex) {
            Logger.getLogger(CadastroProntuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProntuario.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProntuario().setVisible(true);
            }
        });
    }

    public void PreencherTabela(String sql) throws SQLException {
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        modelo.setNumRows(0);

        DateFormat data = new SimpleDateFormat("dd/MM/yyyy");

        while (rs.next()) {
            modelo.addRow(new Object[]{
                data.format(rs.getDate("dataconsulta")),
                rs.getString("descricao")
            });
        }//fim do while

        rs.close();
        stmt.close();

    }//fim do PreecherTabela

    public void LimparCampos() {
        tfDataConsulta.setText("");
        tfDescricao.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton buAlterar;
    private javax.swing.JButton buExcluir;
    private javax.swing.JButton buInserir;
    private javax.swing.JButton buLimparCampos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbNomeMed;
    private javax.swing.JLabel lbNomePac;
    private javax.swing.JFormattedTextField tfDataConsulta;
    private javax.swing.JTextPane tfDescricao;
    // End of variables declaration//GEN-END:variables
}
